kind apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  namespace: b
spec:
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: busybox-b
        image: busybox:1.35.0
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports: []
