kind apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: a
spec:
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: busybox-a
        image: busybox:1.35.0
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports: []
